
["Fuel Items"]
	#Defines items that can be used as fuel
	#Format: [["item-id-1", amount-1], ["item-id-2", amount-2], ...etc]
	Boiler = [["#minecraft:planks", 10], ["minecraft:coal", 37], ["minecraft:charcoal", 37], ["#minecraft:logs_that_burn", 37], ["minecraft:coal_block", 333], ["minecraft:magma_block", 333], ["minecraft:lava_bucket", 1000]]
	Icebox = [["minecraft:snowball", 37], ["minecraft:clay_ball", 37], ["minecraft:snow_block", 333], ["minecraft:ice", 333], ["minecraft:clay", 333], ["minecraft:powder_snow_bucket", 333], ["minecraft:water_bucket", 1000], ["minecraft:packed_ice", 1000]]
	#Negative values indicate cold fuel
	Hearth = [["#minecraft:planks", 10], ["minecraft:coal", 37], ["minecraft:charcoal", 37], ["#minecraft:logs_that_burn", 37], ["minecraft:coal_block", 333], ["minecraft:magma_block", 333], ["minecraft:lava_bucket", 1000], ["minecraft:snowball", -37], ["minecraft:clay_ball", -37], ["minecraft:snow_block", -333], ["minecraft:ice", -333], ["minecraft:clay", -333], ["minecraft:powder_snow_bucket", -333], ["minecraft:water_bucket", -1000], ["minecraft:packed_ice", -1000]]
	#If true, potions can be used as fuel in the hearth
	#This gives all players in range the potion effect
	"Allow Potions in Hearth" = true
	#Potions containing any of these effects will not be allowed in the hearth
	#Format: ["effect_id", "effect_id", ...etc]
	"Blacklisted Potion Effects" = ["minecraft:instant_damage", "minecraft:poison", "minecraft:wither", "minecraft:weakness", "minecraft:mining_fatigue", "minecraft:slowness"]

["Soulspring Lamp"]
	#Defines items that the Soulspring Lamp can use as fuel
	#Format: [["item-id-1", amount-1], ["item-id-2", amount-2], ...etc]
	"Fuel Items" = [["cold_sweat:soul_sprout", 4]]
	#Defines the dimensions that the Soulspring Lamp can be used in
	#Format: ["dimension-id-1", "dimension-id-2", ...etc]
	"Valid Dimensions" = ["minecraft:the_nether"]

[Insulation]
	#Defines the items that can be used for insulating armor in the Sewing Table
	#Format: [["item_id", cold, hot], ["item_id", cold, hot], ...etc]
	#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
	#"cold": The amount of cold insulation the item provides.
	#"hot": The amount of heat insulation the item provides.
	"Insulation Ingredients" = [["alexsmobs:shed_snake_skin", 1.5, 0.0], ["minecraft:purple_wool", 1.5, 0.0], ["minecraft:brown_wool", 1.5, 0.0], ["cold_sweat:hoglin_hide", 0.0, 2.0], ["minecraft:pink_wool", 1.5, 0.0], ["blue_skies:fox_pelt", 1.0, 1.0], ["minecraft:leather_boots", 4.0, 4.0], ["minecraft:lime_wool", 1.5, 0.0], ["alexsmobs:bear_fur", 1.0, 1.0], ["minecraft:magenta_wool", 1.5, 0.0], ["alexsmobs:kangaroo_hide", 0.0, 1.5], ["alexsmobs:bison_fur", 1.0, 1.0], ["minecraft:light_gray_wool", 1.5, 0.0], ["minecraft:cyan_wool", 1.5, 0.0], ["cold_sweat:hoglin_hooves", 0.0, 8.0], ["minecraft:leather_helmet", 4.0, 4.0], ["cold_sweat:fur", 2.0, 0.0], ["minecraft:yellow_wool", 1.5, 0.0], ["minecraft:gray_wool", 1.5, 0.0], ["cold_sweat:hoglin_headpiece", 0.0, 8.0], ["cold_sweat:hoglin_trousers", 0.0, 10.0], ["minecraft:white_wool", 1.5, 0.0], ["minecraft:light_blue_wool", 1.5, 0.0], ["minecraft:green_wool", 1.5, 0.0], ["minecraft:blue_wool", 1.5, 0.0], ["minecraft:leather_chestplate", 6.0, 6.0], ["minecraft:leather", 1.0, 1.0], ["immersiveengineering:ersatz_leather", 1.0, 1.0], ["minecraft:rabbit_hide", 0.0, 1.5], ["cold_sweat:fur_boots", 8.0, 0.0], ["cold_sweat:fur_cap", 8.0, 0.0], ["minecraft:orange_wool", 1.5, 0.0], ["minecraft:red_wool", 1.5, 0.0], ["cold_sweat:fur_pants", 10.0, 0.0], ["cold_sweat:hoglin_tunic", 0.0, 12.0], ["minecraft:leather_leggings", 5.0, 5.0], ["minecraft:black_wool", 1.5, 0.0], ["cold_sweat:fur_parka", 12.0, 0.0]]
	#Defines the items that provide insulation when worn
	#Format: [["item_id", cold, hot], ["item_id", cold, hot], ...etc]
	#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
	#"cold": The amount of cold insulation the item provides.
	#"hot": The amount of heat insulation the item provides.
	"Insulating Armor" = [["cold_sweat:hoglin_headpiece", 0.0, 8.0], ["cold_sweat:hoglin_trousers", 0.0, 10.0], ["cold_sweat:fur_boots", 8.0, 0.0], ["cold_sweat:fur_cap", 8.0, 0.0], ["cold_sweat:fur_pants", 10.0, 0.0], ["cold_sweat:hoglin_tunic", 0.0, 12.0], ["minecraft:leather_leggings", 5.0, 5.0], ["minecraft:leather_helmet", 4.0, 4.0], ["cold_sweat:hoglin_hooves", 0.0, 8.0], ["minecraft:leather_chestplate", 6.0, 6.0], ["cold_sweat:fur_parka", 12.0, 0.0], ["minecraft:leather_boots", 4.0, 4.0]]
	#Defines the items that provide insulation when worn in a curio slot
	#Format: [["item_id", cold, hot], ["item_id", cold, hot], ...etc]
	#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
	#"cold": The amount of cold insulation the item provides.
	#"hot": The amount of heat insulation the item provides.
	"Insulating Curios" = [["irons_spellbooks:frostward_ring", 20.0, 0.0], ["sophisticatedbackpacks:netherite_backpack", 1.0, 1.0], ["sophisticatedbackpacks:gold_backpack", 1.0, 1.0], ["artifacts:aqua_dashers", 0.5, 0.5], ["immersiveengineering:earmuffs", 0.5, 0.5], ["artifacts:scarf_of_invisibility", 0.5, 0.5], ["create:goggles", 0.5, 0.5], ["artifacts:novelty_drinking_hat", 0.5, 0.5], ["artifacts:night_vision_goggles", 0.5, 0.5], ["artifacts:villager_hat", 0.5, 0.5], ["immersiveengineering:powerpack", 1.0, 1.0], ["sophisticatedbackpacks:copper_backpack", 1.0, 1.0], ["artifacts:anglers_hat", 0.5, 0.5], ["irons_spellbooks:fireward_ring", 0.0, 20.0], ["artifacts:snorkel", 0.5, 0.5], ["artifacts:kitty_slippers", 0.5, 0.5], ["artifacts:bunny_hoppers", 0.5, 0.5], ["artifacts:plastic_drinking_hat", 0.5, 0.5], ["artifacts:running_shoes", 0.5, 0.5], ["botania:flight_tiara", 0.5, 0.5], ["sophisticatedbackpacks:iron_backpack", 1.0, 1.0], ["artifacts:cowboy_hat", 0.5, 0.5], ["artifacts:lucky_scarf", 0.5, 0.5], ["sophisticatedbackpacks:diamond_backpack", 1.0, 1.0], ["artifacts:rooted_boots", 0.5, 0.5], ["sophisticatedbackpacks:backpack", 1.0, 1.0], ["artifacts:superstitious_hat", 0.5, 0.5], ["botania:itemfinder", 0.5, 0.5], ["artifacts:flippers", 0.5, 0.5], ["artifacts:steadfast_spikes", 0.5, 0.5], ["artifacts:snowshoes", 0.5, 0.5]]
	#Defines how many insulation slots armor pieces have
	#Format: [head, chest, legs, feet]
	"Insulation Slots" = [4, 6, 5, 4]
	#Defines wearable items that cannot be insulated
	#Format: ["item_id", "item_id", ...etc]
	"Insulation Blacklist" = []
	#Defines insulation items that have the special "chameleon molt" effect
	#Format: [["item_id", insulation, adaptSpeed], ["item_id", insulation, adaptSpeed], ...etc]
	#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
	#"insulation": The amount of insulation the item provides. Will adjust to hot/cold based on the environment.
	#"adaptSpeed": The speed at which the item adapts to the current temperature. Higher values mean faster adaptation (from 0 to 1).
	"Adaptive Insulation Ingredients" = [["cold_sweat:chameleon_molt", 2.0, 0.0085]]

[Consumables]
	#Defines items that affect the player's temperature when consumed
	#Format: [["item_id", amount], ["item_id", amount], ...etc]
	#Negative values are cold foods, positive values are hot foods
	"Temperature-Affecting Foods" = []
	#Defines how much a waterskin will change the player's body temperature by when used
	#Range: > 0
	"Waterskin Strength" = 50

