
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	#Disables certain types
	[general.types]

		[general.types.leaves_type]

			[general.types.leaves_type.biomesoplenty]
				origin = true
				flowering_oak = true
				maple = true
				orange_autumn = true
				yellow_autumn = true
				rainbow_birch = true
				snowblossom = true
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.leaves_type.blue_skies]
				crystallized = true
				crescent_fruit = true
				bluebright = true
				starlit = true
				frostbright = true
				lunar = true
				dusk = true
				maple = true
				comet = true

			[general.types.leaves_type.undergarden]
				smogstem = true
				wigglewood = true
				grongle = true

			[general.types.leaves_type.outer_end]
				azure = true

		[general.types.cake]

			[general.types.cake.blue_skies]
				comet_berry_pie = true

		[general.types.wood_type]

			[general.types.wood_type.blue_skies]
				crystallized = true
				bluebright = true
				starlit = true
				frostbright = true
				lunar = true
				dusk = true
				maple = true
				comet = true

			[general.types.wood_type.biomesoplenty]
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.wood_type.undergarden]
				smogstem = true
				wigglewood = true
				grongle = true

			[general.types.wood_type.betterarcheology]
				rotten = true

			[general.types.wood_type.outer_end]
				azure = true

			[general.types.wood_type.botania]
				livingwood = true
				dreamwood = true

	#Disables specific entries
	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.storagedrawers]
				full_drawers_2 = true
				half_drawers_1 = true
				full_drawers_4 = true
				half_drawers_4 = true
				trim = true
				half_drawers_2 = true
				full_drawers_1 = true

			[general.entries.wood_type.decorative_blocks]
				beam = true
				support = true
				seat = true
				palisade = true

			[general.entries.wood_type.create]
				window = true
				window_pane = true

			[general.entries.wood_type.farmersdelight]
				cabinet = true

			[general.entries.wood_type.vct]
				crafting_table = true

